* Redis notes

** Redis Cluster vs Sentinel

- Cluster: sharding (performance). 
- Sentinel: HA (high availibility).

* Redis workflow

Steps:

1. Is Cluster Unconfigured? cluster. =redis info -h redis-cluster-0.redis-cluster

* Redis Operator examples

Lot of examples, but that assign redis slots only this one:

- https://github.com/AmadeusITGroup/Redis-Operator

Links:

** Kubedb example

KubeDB uses *PodDisruptionBudget* to ensure that majority of these cluster replicas are available during
voluntary disruptions so that quorum is maintained and no data loss is occurred.


https://kubedb.com (backup, clone)

https://kubedb.com/docs/v2020.11.12/guides/redis/

An important concept:

RedisVersion CR: https://kubedb.com/docs/v2020.11.12/guides/redis/concepts/catalog/

The redis part: https://github.com/kubedb/redis/

* Operator madurity

1. Install

* Build

All the commands I use to build the operator. To run the

#+PROPERTY: header-args:sh  :session *sh*  :results output verbatim code replace

Clean all:

#+BEGIN_SRC sh
OP=redis-operator
OP_KIND=Redis
OP_GROUP=redis
OPERATOR_IMAGE_REPO=redisoperator
#+END_SRC

Clean all:

#+BEGIN_SRC sh
echo "Warning! deleting all!"
# rm -rf $HOME/src/$OP
#+END_SRC


#+BEGIN_SRC sh
# OP is the operator name
mkdir -p $HOME/src/$OP
cd $HOME/src/$OP
operator-sdk init --domain=danieldorado.github.io --repo=github.com/danieldorado/$OP
#+END_SRC

Create CRD and Controller.

-  ~main.go~ initializes the Manager.

#+BEGIN_SRC sh
operator-sdk create api --group $OP_GROUP --version v1alpha1 --kind $OP_KIND --resource=true --controller=true
#+END_SRC

Fill scaffolds. 

** TODO Define the API. Redis Types.

[[file:api/v1alpha1/redis_types.go]]

https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/#define-the-api

Properties:

- Size: redis nodes number.

Invoke the =controller-gen= to generate =*.deepcopy.go= that implements =runtime.Object= interface:

#+BEGIN_SRC sh
make generate
#+END_SRC

Generate CRD manifests:

#+BEGIN_SRC sh
make manifests
#+END_SRC

Manifest: =config/crd/bases/redis.danieldorado.github.io_redis.yaml=

*** TODO Use OpenAPI

Use OpenAPI to validate: [[https://sdk.operatorframework.io/docs/building-operators/golang/tutorial/#openapi-validation]]


** TODO Define the Controller. Redis Controller.

- [[file:controllers/redis_controller.go]]

** Build and Push operator image

Kubebuilder is a prerequisite.

#+BEGIN_SRC sh
make docker-build docker-push IMG=danieladf/$OPERATOR_IMAGE_REPO:0.0.2
#+END_SRC

** Install the CRD and deploy to the cluster the Deployment

Create and edit the role patch: [[file:config/default/role_patch.yml]] patch [[file:config/rbac/role.yaml]]

Alternatively to deploy you can run local: =make run=

#+BEGIN_SRC sh
make install
make deploy IMG=danieladf/$OPERATOR_IMAGE_REPO:0.0.2
#+END_SRC

- Deployed in: =namespace/redis-operator-system created=

** Create a sample.

#+BEGIN_SRC  sh
oc project default
oc apply -f config/samples/redis_v1alpha1_redis.yaml
#+END_SRC

Clean all:

#+BEGIN_SRC sh
make uninstall
oc delete project/redis-operator-system
#+END_SRC


* Test

Controller test:

#+BEGIN_SRC sh
go test ./controllers/ -v -ginkgo.v
#+END_SRC

* TEST

Using envtest with ginkgo and gomega.

- All nodes deleted at same time.

* Advancing topics

** Conditions

#+BEGIN_SRC go
import (
    "github.com/operator-framework/operator-lib/status"
)

type MyAppStatus struct {
    // Conditions represent the latest available observations of an object's state
    Conditions status.Conditions `json:"conditions"`
}
#+END_SRC


** Expectations

In-memory expectations.

Guarantees.

** reflect.DeepEqual

Does not work because of mutating fields added. Use a annotation hash with our fields.
#+BEGIN_SRC go
hash := HashObject(expected)
expected.Annotations[ResourceHash] = hash
#+END_SRC
