# permissions for end users to edit redis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redis-editor-role
rules:
- apiGroups:
  - redis.danieldorado.github.io
  resources:
  - redis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - redis.danieldorado.github.io
  resources:
  - redis/status
  verbs:
  - get
